### ISSUE TITLE
Link for docker-compose 

### ISSUE THREAD

**Issue by ManuelLevi** [RocketChat/docs-old#1336]
Hi,

On the page [docker-containers](https://rocket.chat/docs/installation/docker-containers/), it's recommended to the user to install 

> Docker-Compose version 1.4.2 

However, with this version, you won't be able to run `docker-compose.yml` as it does not, as far as I know, support the `version: '2'` specification in the same tutorial.

We've had some problems following this tutorial, would be great if someone from the organization would try to follow all the given commands!

Thanks

**Comment by reetp** [comment]
@rocket-cat close

Closing as the documentation has been updated

For anyone looking for an older version compose I use this for v1.5.2

Note that this uses a local mongo DB, not a docker version.

```
rocketchat:
    image: rocketchat/rocket.chat:1.3.0
    container_name: rocketchat
    environment:
        - MONGO_URL=mongodb://127.0.0.1:27017/rocketchat?replSet=rs0
        - MONGO_OPLOG_URL=mongodb://127.0.0.1:27017/local?replSet=rs0
        - ROOT_URL=https://chat.mydomain.com
        - MAIL_URL=smtp://127.0.0.1:25
        - HTTP_FORWARDED_COUNT=1
        - Accounts_UseDNSDomainCheck=True
    ports:
        - 3000:3000
# Depends on usage
#    net: "host"
# Specify an absolute path mapping
    volumes:
        - /opt/uploads/:/opt/uploads/
    restart: on-failure:2
# Might need the UID/GID rather than name
# user: dockerroot:dockerroot
    user: 393:391
```
