### ISSUE TITLE
AWS Setup: Cannot start service mongo.

### ISSUE THREAD

**Issue by lucasfarias** [RocketChat/docs-old#1659]
In the last step of the aws setup, 
when I do: `/var/www/rocket.chat$ docker-compose up -d`
I'm getting the errror:

> Creating rocketchat_mongo_1 ... error
> 
> ERROR: for rocketchat_mongo_1  Cannot start service mongo: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:297: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown
> 
> ERROR: for mongo  Cannot start service mongo: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:297: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown
> ERROR: Encountered errors while bringing up the project.

Am I doing something wrong? Or this is actually an issue?

Here's the docker-compose.yml

```
version: '2'

services:
 rocketchat:
  image: rocket.chat:latest
  restart: unless-stopped
  volumes:
   - ./uploads:/app/uploads
  environment:
   - PORT=3000
   - ROOT_URL=https://my.host
   - MONGO_URL=mongodb://mongo:27017/rocketchat
   - MONGO_OPLOG_URL=mongodb://mongo:27017/local
   - Accounts_UseDNSDomainCheck=True
  depends_on:
   - mongo
  ports:
   - 3000:3000

 mongo:
  image: mongo
  restart: unless-stopped
  volumes:
   - .data/runtime/db:/data/db
   - ./data/dump:/dump
  command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1

 mongo-init-replica:
  image: mongo
  command: 'bash -c "for i in `seq 1 30`; do mongo mongo/rocketchat --eval \"rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})\" && s=$$? && break || s=$$?; echo \"Tried $$i times. Waiting 5 secs...\"; sleep 5; don$
  depends_on:
   - mongo
```

when I run 

`docker ps -a`

the output is:

>

> CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
> 83dfd468337c        mongo               "docker-entrypoint.s…"   22 seconds ago      Created             27017/tcp           rocketchat_mongo_1
